# Generated by Django 5.0.9 on 2024-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Student',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=240, verbose_name='Name')),
        #         ('email', models.EmailField(max_length=254)),
        #         ('document', models.CharField(max_length=20, verbose_name='Document')),
        #         ('phone', models.CharField(max_length=20)),
        #         ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='StudentQuest',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('question_text', models.CharField(max_length=200)),
        #         ('pub_date', models.DateTimeField(verbose_name='date published')),
        #     ],
        # ),
    ]
