# Generated by Django 5.0.9 on 2024-10-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzx', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='StudentEnroll',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('enroll_text', models.CharField(max_length=200)),
        #         ('enroll_date', models.DateTimeField(verbose_name='date published')),
        #     ],
        # ),
    ]
