# Generated by Django 5.0.9 on 2024-10-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzx', '0002_studentenroll'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='studentenroll',
        #     name='phone',
        #     field=models.CharField(max_length=20, null=True),
        # ),
    ]
