# Generated by Django 5.0.9 on 2024-10-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hzx', '0004_studentinfo'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Student',
        # ),
        # migrations.DeleteModel(
        #     name='StudentQuest',
        # ),
    ]
