# Generated by Django 5.0.9 on 2024-10-27 23:24

from django.db import migrations

def create_data(apps, schema_editor):
    StudentInfo = apps.get_model('hzx', 'StudentInfo')
    StudentInfo(name="Julia Han", email="julia@email.com", document="0205478965", phone="12332145").save()


class Migration(migrations.Migration):

    dependencies = [
        ('hzx', '0005_delete_student_delete_studentquest'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
